In [29]:
import pandas as pd

df = pd.read_csv("cleaned_integrated_materials.csv")
df.head()

,Material ID,Packaging Type,Material Type,Suitable Product Categories,Recommended Packaging Use Cases,Supplier Region,Recyclability (%),Recyclability Category,Recycled Content (%),Reusability (%),...,CO2 Emission per kg (estimated),Waste Reduction Impact (%),Sustainability Target Progress (%),Load Handling Score,Moisture Resistance Score,Thermal Resistance Score,Cost per Unit (USD),Annual Usage (units),Total Material Weight (tons),Supplier Sustainability Compliance (%)
0,MAT_0001,Cardboard Boxes,Cardboard,"E-commerce, Food & Beverage, Consumer Goods, A...",Last-mile delivery and primary e-commerce pack...,EMEA,98.0,High,79.0,49.0,...,0.54,61.0,88.0,6.0,5.0,4.0,2.24,101260.0,790.0,85.0
1,MAT_0002,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,APAC,100.0,High,93.0,31.0,...,0.32,68.0,98.0,3.0,3.0,3.0,1.82,73961.0,545.0,88.0
2,MAT_0003,Steel Racks & Containers,Steel,"Heavy Industrial Components, High-Security Goods","Secure, high-load international shipping and l...",AMERICAS,87.0,High,78.0,100.0,...,3.25,85.0,79.0,8.0,9.0,9.0,25.00,14649.0,4979.0,88.0
3,MAT_0004,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,ROW,100.0,High,89.0,31.0,...,0.31,69.0,87.0,1.0,1.0,4.0,2.43,75036.0,656.0,81.0
4,MAT_0005,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,LATAM,100.0,High,92.0,28.0,...,0.31,61.0,89.0,3.0,2.0,3.0,1.69,69209.0,549.0,81.0

In [30]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
    .str.replace("%", "percent", regex=False)
)
df.columns

Index(['material_id', 'packaging_type', 'material_type',
       'suitable_product_categories', 'recommended_packaging_use_cases',
       'supplier_region', 'recyclability_percent', 'recyclability_category',
       'recycled_content_percent', 'reusability_percent',
       'biodegradation_time_days', 'end-of-life_disposal_percent',
       'carbon_footprint_kg_co2/unit', 'co2_emission_per_kg_estimated',
       'waste_reduction_impact_percent',
       'sustainability_target_progress_percent', 'load_handling_score',
       'moisture_resistance_score', 'thermal_resistance_score',
       'cost_per_unit_usd', 'annual_usage_units', 'total_material_weight_tons',
       'supplier_sustainability_compliance_percent'],
      dtype='object')

In [31]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
    .str.replace("%", "percent", regex=False)
)
df.columns

Index(['material_id', 'packaging_type', 'material_type',
       'suitable_product_categories', 'recommended_packaging_use_cases',
       'supplier_region', 'recyclability_percent', 'recyclability_category',
       'recycled_content_percent', 'reusability_percent',
       'biodegradation_time_days', 'end-of-life_disposal_percent',
       'carbon_footprint_kg_co2/unit', 'co2_emission_per_kg_estimated',
       'waste_reduction_impact_percent',
       'sustainability_target_progress_percent', 'load_handling_score',
       'moisture_resistance_score', 'thermal_resistance_score',
       'cost_per_unit_usd', 'annual_usage_units', 'total_material_weight_tons',
       'supplier_sustainability_compliance_percent'],
      dtype='object')

In [32]:
target = "material_type"
y = df[target]
y.head()

0          Cardboard
1    Paper/Bio-Based
2              Steel
3    Paper/Bio-Based
4    Paper/Bio-Based
Name: material_type, dtype: object

In [33]:
X = df.drop(columns=[target])
X.head()

,material_id,packaging_type,suitable_product_categories,recommended_packaging_use_cases,supplier_region,recyclability_percent,recyclability_category,recycled_content_percent,reusability_percent,biodegradation_time_days,...,co2_emission_per_kg_estimated,waste_reduction_impact_percent,sustainability_target_progress_percent,load_handling_score,moisture_resistance_score,thermal_resistance_score,cost_per_unit_usd,annual_usage_units,total_material_weight_tons,supplier_sustainability_compliance_percent
0,MAT_0001,Cardboard Boxes,"E-commerce, Food & Beverage, Consumer Goods, A...",Last-mile delivery and primary e-commerce pack...,EMEA,98.0,High,79.0,49.0,188.0,...,0.54,61.0,88.0,6.0,5.0,4.0,2.24,101260.0,790.0,85.0
1,MAT_0002,Protective Fillers (Paper/Biodegradable),"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,APAC,100.0,High,93.0,31.0,65.0,...,0.32,68.0,98.0,3.0,3.0,3.0,1.82,73961.0,545.0,88.0
2,MAT_0003,Steel Racks & Containers,"Heavy Industrial Components, High-Security Goods","Secure, high-load international shipping and l...",AMERICAS,87.0,High,78.0,100.0,180208.0,...,3.25,85.0,79.0,8.0,9.0,9.0,25.00,14649.0,4979.0,88.0
3,MAT_0004,Protective Fillers (Paper/Biodegradable),"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,ROW,100.0,High,89.0,31.0,65.0,...,0.31,69.0,87.0,1.0,1.0,4.0,2.43,75036.0,656.0,81.0
4,MAT_0005,Protective Fillers (Paper/Biodegradable),"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,LATAM,100.0,High,92.0,28.0,122.0,...,0.31,61.0,89.0,3.0,2.0,3.0,1.69,69209.0,549.0,81.0

In [34]:
X.to_csv("X_raw.csv", index=False)
y.to_csv("y_raw.csv", index=False)

print("SUCCESS: Files saved")

SUCCESS: Files saved