# EcoPackAI — Dataset Preparation for Model Development
**Module:** Define Target Variables & Features (DEC 12)

This notebook prepares the dataset for model development by:
- selecting appropriate target variables
- identifying valid input features
- preventing data leakage
- creating feature (`X`) and target (`y`) datasets

No feature engineering or model training is performed in this notebook.

In [1]:
import pandas as pd
from pathlib import Path

In [3]:
DATA_PATH = Path("./final/materials_cleaned.parquet")

df = pd.read_parquet(DATA_PATH)

df.shape

(404, 23)

In [4]:
df.columns.tolist()

['Material ID',
 'Packaging Type',
 'Material Type',
 'Suitable Product Categories',
 'Recommended Packaging Use Cases',
 'Supplier Region',
 'Recyclability (%)',
 'Recyclability Category',
 'Recycled Content (%)',
 'Reusability (%)',
 'Biodegradation Time (days)',
 'End-of-Life Disposal (%)',
 'Carbon Footprint (kg CO2/unit)',
 'CO2 Emission per kg (estimated)',
 'Waste Reduction Impact (%)',
 'Sustainability Target Progress (%)',
 'Load Handling Score',
 'Moisture Resistance Score',
 'Thermal Resistance Score',
 'Cost per Unit (USD)',
 'Annual Usage (units)',
 'Total Material Weight (tons)',
 'Supplier Sustainability Compliance (%)']

In [5]:
df.head()

,Material ID,Packaging Type,Material Type,Suitable Product Categories,Recommended Packaging Use Cases,Supplier Region,Recyclability (%),Recyclability Category,Recycled Content (%),Reusability (%),...,CO2 Emission per kg (estimated),Waste Reduction Impact (%),Sustainability Target Progress (%),Load Handling Score,Moisture Resistance Score,Thermal Resistance Score,Cost per Unit (USD),Annual Usage (units),Total Material Weight (tons),Supplier Sustainability Compliance (%)
0,MAT_0001,Cardboard Boxes,Cardboard,"E-commerce, Food & Beverage, Consumer Goods, A...",Last-mile delivery and primary e-commerce pack...,EMEA,98,High,79.0,49.0,...,0.54,61.0,88.0,6.0,5.0,4.0,2.24,101260.0,790.0,85.0
1,MAT_0002,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,APAC,100,High,93.0,31.0,...,0.32,68.0,98.0,3.0,3.0,3.0,1.82,73961.0,545.0,88.0
2,MAT_0003,Steel Racks & Containers,Steel,"Heavy Industrial Components, High-Security Goods","Secure, high-load international shipping and l...",AMERICAS,87,High,78.0,100.0,...,3.25,85.0,79.0,8.0,9.0,9.0,25.00,14649.0,4979.0,88.0
3,MAT_0004,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,ROW,100,High,89.0,31.0,...,0.31,69.0,87.0,1.0,1.0,4.0,2.43,75036.0,656.0,81.0
4,MAT_0005,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,LATAM,100,High,92.0,28.0,...,0.31,61.0,89.0,3.0,2.0,3.0,1.69,69209.0,549.0,81.0

## Dataset Overview

This dataset contains material-level information related to:
- sustainability metrics
- cost and usage patterns
- performance and resistance scores
- supplier compliance
- product category and use-case applicability

The dataset is clean (no missing values) and ready for target/feature definition.

## Target Variable Identification

Based on the EcoPackAI project objective — recommending sustainable and
cost-effective packaging materials — the following composite outcomes are
identified as candidate targets:

- Final_Recommendation_Score
- CO2_Impact_Index
- Cost_Efficiency_Index
- Material_Suitability_Score

These targets represent continuous scores and are suitable for regression tasks.

In [12]:
# Target variables are defined conceptually at this stage.
# They will be materialized after feature engineering.

PRIMARY_TARGET = "Final_Recommendation_Score"

SECONDARY_TARGETS = [
    "CO2_Impact_Index",
    "Cost_Efficiency_Index",
    "Material_Suitability_Score"
]

PRIMARY_TARGET, SECONDARY_TARGETS

('Final_Recommendation_Score',
 ['CO2_Impact_Index', 'Cost_Efficiency_Index', 'Material_Suitability_Score'])

In [7]:
EXCLUDED_COLUMNS = [
    "Material ID",
    PRIMARY_TARGET,
    *SECONDARY_TARGETS
]

EXCLUDED_COLUMNS

['Material ID',
 'Final_Recommendation_Score',
 'CO2_Impact_Index',
 'Cost_Efficiency_Index',
 'Material_Suitability_Score']

### Why these columns are excluded
- **Material ID**: Identifier, no predictive value
- **Target variables**: Excluded to prevent target leakage

In [8]:
FEATURE_COLUMNS = [col for col in df.columns if col not in EXCLUDED_COLUMNS]

len(FEATURE_COLUMNS)

22

In [9]:
FEATURE_COLUMNS

['Packaging Type',
 'Material Type',
 'Suitable Product Categories',
 'Recommended Packaging Use Cases',
 'Supplier Region',
 'Recyclability (%)',
 'Recyclability Category',
 'Recycled Content (%)',
 'Reusability (%)',
 'Biodegradation Time (days)',
 'End-of-Life Disposal (%)',
 'Carbon Footprint (kg CO2/unit)',
 'CO2 Emission per kg (estimated)',
 'Waste Reduction Impact (%)',
 'Sustainability Target Progress (%)',
 'Load Handling Score',
 'Moisture Resistance Score',
 'Thermal Resistance Score',
 'Cost per Unit (USD)',
 'Annual Usage (units)',
 'Total Material Weight (tons)',
 'Supplier Sustainability Compliance (%)']

## Feature Groups Used

The selected features include:

- Sustainability indicators (recyclability, carbon footprint, waste reduction)
- Performance scores (load handling, moisture and thermal resistance)
- Cost and usage metrics
- Supplier sustainability compliance
- Product category compatibility
- Use-case applicability

These features are available before decision-making and do not introduce leakage.

In [13]:
X = df[FEATURE_COLUMNS]

X.shape

(404, 22)

In [14]:
# Ensure no missing values
# Validate features only (targets not yet materialized)
X.isnull().sum().sum()

0

In [15]:
# Ensure target not present in features
PRIMARY_TARGET in X.columns

False

In [16]:
X.head()

,Packaging Type,Material Type,Suitable Product Categories,Recommended Packaging Use Cases,Supplier Region,Recyclability (%),Recyclability Category,Recycled Content (%),Reusability (%),Biodegradation Time (days),...,CO2 Emission per kg (estimated),Waste Reduction Impact (%),Sustainability Target Progress (%),Load Handling Score,Moisture Resistance Score,Thermal Resistance Score,Cost per Unit (USD),Annual Usage (units),Total Material Weight (tons),Supplier Sustainability Compliance (%)
0,Cardboard Boxes,Cardboard,"E-commerce, Food & Beverage, Consumer Goods, A...",Last-mile delivery and primary e-commerce pack...,EMEA,98,High,79.0,49.0,188.0,...,0.54,61.0,88.0,6.0,5.0,4.0,2.24,101260.0,790.0,85.0
1,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,APAC,100,High,93.0,31.0,65.0,...,0.32,68.0,98.0,3.0,3.0,3.0,1.82,73961.0,545.0,88.0
2,Steel Racks & Containers,Steel,"Heavy Industrial Components, High-Security Goods","Secure, high-load international shipping and l...",AMERICAS,87,High,78.0,100.0,180208.0,...,3.25,85.0,79.0,8.0,9.0,9.0,25.00,14649.0,4979.0,88.0
3,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,ROW,100,High,89.0,31.0,65.0,...,0.31,69.0,87.0,1.0,1.0,4.0,2.43,75036.0,656.0,81.0
4,Protective Fillers (Paper/Biodegradable),Paper/Bio-Based,"Fragile Items, Cosmetics, Pharmaceuticals, Int...",Void-fill and cushioning for fragile products,LATAM,100,High,92.0,28.0,122.0,...,0.31,61.0,89.0,3.0,2.0,3.0,1.69,69209.0,549.0,81.0

In [19]:
from pathlib import Path

OUTPUT_DIR = Path("./model_input")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

X.to_csv(OUTPUT_DIR / "X_raw.csv", index=False)

print("X dataset saved successfully.")
print("Target (y) will be generated after feature engineering.")

X dataset saved successfully.
Target (y) will be generated after feature engineering.

## Summary

In this notebook:
- Target variables were **defined conceptually**
- Valid input features were selected
- Data leakage was explicitly prevented
- Feature dataset (`X_raw.csv`) was created and saved

## Next Steps
- Materialize feature-engineered target variables
- Generate `y_raw.csv`
- Train regression models using prepared X and y